import { build } from 'esbuild'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(root, 'lib')
const watch = process.argv.includes('--watch')

/**
 * Bundles that the DSH shell provides at runtime. `require()`-ing any of these
 * inside the lazy-CJS factory resolves to the host's own instances. Everything
 * else must be bundled into the plugin payload.
 */
const HOST_PROVIDED = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
]

const PLUGIN_ID = '@a9i5k4/dsh-literature'

const nodeOptions = {
  entryPoints: [resolve(root, 'src/node/index.js')],
  outfile: resolve(outDir, 'index.js'),
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  sourcemap: false,
  logLevel: 'info',
  // Keep the host's cordis instance and node builtins out of the bundle.
  external: ['@deepseek-ai/cordis', '@deepseek-ai/*'],
  banner: { js: '/* @a9i5k4/dsh-literature — DSH host half. Generated by build.mjs, do not edit. */' },
}

/**
 * pdf.js needs its worker as a separate script. The DSH module loader only ever
 * serves `/plugins/<id>/client.js`, so the worker bundle is inlined as a string
 * and rehydrated through a Blob URL at runtime.
 */
async function bundleWorkerSource() {
  let workerEntry
  try {
    const pkgPath = resolve(root, 'node_modules/pdfjs-dist/package.json')
    const pkg = JSON.parse(await readFile(pkgPath, 'utf8'))
    workerEntry = resolve(root, 'node_modules/pdfjs-dist', pkg.exports?.['./build/pdf.worker.min.mjs'] ?? 'build/pdf.worker.min.mjs')
  } catch {
    console.warn('[dsh-literature] pdfjs-dist not found — skipping worker bundle (viewer will use the fake worker)')
    return ''
  }

  const result = await build({
    entryPoints: [workerEntry],
    bundle: true,
    write: false,
    platform: 'browser',
    target: 'es2020',
    format: 'iife',
    minify: true,
    legalComments: 'none',
    logLevel: 'silent',
  })
  const text = result.outputFiles[0].text
  console.log(`[dsh-literature] pdf.js worker bundled: ${(text.length / 1024).toFixed(0)} KB`)
  return text
}

const banner = `window.__ModuleLoader__.load({
  id: ${JSON.stringify(PLUGIN_ID)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
`
const footer = `
    return module.exports;
  }
});
`

async function clientOptions() {
  const workerSrc = await bundleWorkerSource()
  return {
    entryPoints: [resolve(root, 'src/client/index.cjs')],
    outfile: resolve(outDir, 'client.js'),
    bundle: true,
    platform: 'browser',
    target: 'es2020',
    format: 'cjs',
    minify: true,
    sourcemap: false,
    logLevel: 'info',
    external: HOST_PROVIDED,
    loader: { '.css': 'text', '.png': 'dataurl', '.svg': 'dataurl' },
    define: {
      __PDFJS_WORKER_SRC__: JSON.stringify(workerSrc),
      __PLUGIN_ID__: JSON.stringify(PLUGIN_ID),
    },
    banner: { js: banner },
    footer: { js: footer },
  }
}

await mkdir(outDir, { recursive: true })

if (watch) {
  const clientOpts = await clientOptions()
  const [{ context: nodeCtx }, { context: clientCtx }] = await Promise.all([
    import('esbuild').then((m) => m.context(nodeOptions)),
    import('esbuild').then((m) => m.context(clientOpts)),
  ])
  await Promise.all([nodeCtx.watch(), clientCtx.watch()])
  console.log('[dsh-literature] watching src/ …')
} else {
  await build(nodeOptions)
  await build(await clientOptions())
  console.log('[dsh-literature] built lib/index.js and lib/client.js')
}
